<html>
<head>
 <meta http-equiv="Content-Type" content="text/html; charset=windows-1251" />
 <title><?php echo $title; ?></title>
 <style><!--
  .bla-bla {}
  BODY { padding: 0px; margin: 10px; font-family: Arial; font-size: 11px; background-color: #ffffff; color: #ff0000; }
  #error { border-width: 1px; border-style: solid; border-color: <?php echo $colorBorder; ?>; padding: 10px; background-color: <?php echo $color; ?> }
 //-->
 </style>
</head>
<body>
 <div id="error"><?php echo $errstr; ?></div>
</body>
</html>
