 <table>
  <tr>
   <th width="80%" colspan="2">Требования к кандидату</th>
   <th width="20%">Контактная информация</th>
  </tr>
  <tr class="td1">
   <td>Оклад:</td>
   <td width="80%"><?php echo $vac['oklad']; ?></td>
   <td width="20%" rowspan="10" valign="top"><?php echo $vac['contacts']; ?></td>
  </tr>
  <tr class="td2">
   <td>Место жительства:</td>
   <td><?php echo $vac['live']; ?></td>
  </tr>
  <tr class="td1">
   <td>Тип работы:</td>
   <td><?php echo $vac['type']; ?></td>
  </tr>
  <tr class="td2">
   <td>Компенсационный пакет:</td>
   <td><?php echo $vac['social']; ?></td>
  </tr>
  <tr class="td1">
   <td>График работы:</td>
   <td><?php echo $vac['grafik']; ?></td>
  </tr>
  <tr class="td2">
   <td>Должностные обязанности:</td>
   <td><?php echo $vac['obyazanosti']; ?></td>
  </tr>
  <tr class="td1">
   <td>Возраст:</td>
   <td><?php echo $vac['year']; ?></td>
  </tr>
  <tr class="td2">
   <td>Пол:</td>
   <td><?php echo $vac['sex']; ?></td>
  </tr>
  <tr class="td1">
   <td>Образование:</td>
   <td><?php echo $vac['education']; ?></td>
  </tr>
  <tr class="td2">
   <td nowrap="nowrap">Требования к квалификации:</td>
   <td><?php echo $vac['treb']; ?></td>
  </tr>
 </table>