<html>
<head>
  <title>{THEME}</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <style type="text/css">
    A { color: #6eccff; text-decoration: underline; }
    BODY { margin: 0px; padding: 0px; background-color: #ffffff; color: #000000; font-family: Arial; font-size: 12px; font-weight: normal; }
    IMG { border: 0px; }
    TABLE { font-family: Arial; font-size: 12px; color: #000000; }
    H1 { color: #000000; font-size: 16px; margin: 20 0 20 0; font-weight: normal; }
    H2 { font-size: 14px; color: #000000; margin: 0 0 10 0; }
  </style>
</head>
<body>
<table align="center" width="660px" border="0" cellpadding="10" cellspacing="0">
<tr>
<td>
<div style="width:100%; background:#2B2820; margin:0 0 20px;">
<div style="padding:10px 15px;">
<img src="logo.png" alt="r2photos logo" width="147" height="147" />
</div>
</div>
</td>
</tr>
</table>
{TEXT}
<table align="center" width="640px" border="0" cellpadding="10" cellspacing="0" bgcolor="#E7E7E7">
  <tr>
    <td>
      <p><a href="http://r2photos.ru/">r2photos.ru</a></p>
      <p>Тел.: <a href="tel:+74956418153">+7 495-641-81-53</a>, <a href="tel:+79269561155">+7 926-956-11-55</a></p>
      <p>E-mail: <a href="mailto:r2photos@mail.ru">r2photos@mail.ru</a></p></td>
  </tr>
</table>
</body>
</html>