<div class="popup-dialog-wrapper photographer">
  <h1>Заказать фотосессию у фотографа</h1>
  <?php $form->header(); ?>
  <?php echo $alert ? '<span class="alert">'.$alert.'</span>' : ''; ?>
  <input type="hidden" name="photographer_id" value="<?php echo $photographerId; ?>" />
  <label>
    <div class="form-name">Имя:<span class="required">*</span></div>
    <div class="form-value"><?php $form->field('fio', 'data-rule-regexp="[a-zA-Zа-яА-Я]+" data-msg-regexp="Укажите Ваше имя!"'); ?></div>
  </label>
  <div class="clearfix"></div>
  <label>
    <div class="form-name">Телефон:<span class="required">*</span></div>
    <div class="form-value"><?php $form->field('phone', ' data-rule-regexp="[0-9]{3,}" data-msg-regexp="Укажите Ваш контактный телефон!" '); ?></div>
  </label>
  <div class="clearfix"></div>
  <label>
    <div class="form-name">E-mail:</div>
    <div class="form-value"><?php $form->field('email'); ?></div>
  </label>
  <div class="clearfix"></div>
  <label>
    <div class="form-name">Дополнительно:</div>
    <div class="form-value"><?php $form->field('text'); ?></div>
  </label>
  <div class="clearfix"></div>
  <label>
    <div class="form-name">&nbsp;</div>
    <div class="form-value"><button type="submit" class="btn wide" type="submit"><span>Отправить</span></button></div>
  </label>
  <div class="clearfix"></div>
  <?php $form->footer(); ?>
</div>
