<div class="box portfolio">
    <br><br>
    <div class="h1 align">Фотографии клиентов</divh1>
        <div class="slider-box">
            <div class="s-slider-portfolio-prev"></div>
            <div class="s-slider-portfolio-next"></div>

            <div class="sale-slider" data-component="site/ui/front/slider"
                 data-attrs="<?php echo htmlspecialchars(json_encode(array('prevButton' => '.slider-box .s-slider-portfolio-prev', 'nextButton' => '.slider-box .s-slider-portfolio-next', 'autoSlide' => true, 'autoSlideTimer' => 1000))); ?>">
                <div class="slider">
                    <?php foreach ($itemsList as $item) { ?>
                        <div class="slide">
                            <div class="certificate-photos">
                                <a href="/photos"
                                   title="<?php echo htmlspecialchars($item['name']); ?>">
                                    <img src="<?php echo $item['picture'] ?>" width="460" height="322" alt=""></a>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="clearfix"></div>
