<div class="certificate-photos" data-component="site/ui/front/photos-lazy-load" data-title="true" data-rel="true">
    <?php foreach( $itemsList as $item ) {
        $rel = 'pictures-list';
        ?>
        <a href="<?php echo $item['picture']; ?>" rel="<?php echo $rel; ?>" class="item" data-picture="<?php echo $item['picture']; ?>" title="<?php echo htmlspecialchars( $item['name'] ); ?>">
            <img src="<?php echo /*'/thumbs-dev/360x1440/', */$item['picture']; ?>" />
            <span><?php echo $item['name']; ?></span>
        </a>

        <div class="hidden">
            <?php foreach( $item['_photos'] as $photo ) { ?>
                <a href="<?php echo $photo['picture'] ?>" rel="<?php echo $rel; ?>" title="<?php echo htmlspecialchars( $photo['name'] ); ?>"><?php echo $photo['picture']; ?></a>
            <?php } ?>
        </div>
    <?php } ?>
</div>
<div id="loadingbar"
     style="display:none;position:fixed;bottom:0;left:0;right:0;background-color:#000;color:#FFF;text-align:center;">
    <b><i>Loading next 50...</i></b>
</div>
<input type="hidden" value='6' id="start_load_from"/>

<div class="clearfix"></div>

