<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
 <title><?php echo Site::GetParms('projectName'); ?> || администратор сайта</title>
 <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
 <base href="<?php echo Site::GetBaseRef(); ?>">
 <link href="/css/admin.css" rel="stylesheet" type="text/css">
 <?php JS::dump(); ?>
</head>
<body>
<div class="wrapper topBgr">
 <div class="header pr20 pl20 pt20">
  <?php if (defined("UID_ADMIN") && UID_ADMIN > 0) { ?><div class="pngFix logout fr ml20"><a href="logout.htm">Выход</a></div><?php } ?>
  <div class="topText fr" align="right">
   <div>Система управления сайтом <a href="<?php echo Site::GetParms('siteRef'); ?>" target="_blank">www.<?php echo mb_strtolower(Site::GetParms('projectName'), 'utf-8'); ?>.ru</a></div>
   <?php if (defined("UID_ADMIN") && UID_ADMIN > 0) { ?><div>Вы авторизовались как "<?php echo UID_FIO; ?>"</div><?php } ?>
  </div>
  <div class="clear"></div>
  <div class="h20"></div>
  <?php include(Site::GetTemplate('layout', 'menu')); ?>
 </div>
 <div class="content pr20 pl20"><?php echo $content; ?></div>
 <div class="push"></div>
</div>
<div class="footer pr20 pl20"><div class="copyBgr"><div class="copyL"><div class="copyR pr20"><p>&copy; <a href="http://www.interlabs.ru/" target="_blank">InterLabs</a> <?php echo date('Y') ?>. <a href="http://www.interlabs-design.ru/" target="_blank">Дизайн</a>, <a href="http://www.interlabs-style.ru/" target="_blank">разработка</a>, <a href="http://www.interlabs-promo.ru/" target="_blank">продвижение</a> сайтов.</p></div></div></div></div>
</body>
</html>