<html>
<head>
 <title><?php echo Site::GetParms('projectName'); ?> || администратор сайта</title>
 <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
 <base href="<?php echo Site::GetBaseRef(); ?>">
 <link href="/css/admin.css" rel="stylesheet" type="text/css">
</head>
<body>
<table class="wh100">
 <tr><td align="center" class="wh100"><?php echo $content; ?></td></tr>
 <tr><td><div class="copyBgr mr20 ml20 mb20"><div class="copyL"><div class="copyR pr20"><p>&copy; <a href="http://www.interlabs.ru/" target="_blank">InterLabs</a> <?php echo date('Y') ?>. <a href="http://www.interlabs-design.ru/" target="_blank">Дизайн</a>, <a href="http://www.interlabs-style.ru/" target="_blank">разработка</a>, <a href="http://www.interlabs-promo.ru/" target="_blank">продвижение</a> сайтов.</p></div></div></div></td></tr>
</table>
</body>
</html>
