<html>
<head>
 <title><?php echo $parms['subject']; ?></title>
</head>
<body topmargin="0" leftmargin="0" style="background-color: #ffffff; color: #000000; font-family: Arial,Helvetica,clean,sans-serif; font-size: 14px; font-weight: normal;">
<table width="800" height="<?php echo $parms['iwh'][1]; ?>" border="0" cellpadding="0" cellspacing="0" style="background-color: #ffffff;">
 <tr>
  <td style="padding-top: 30px; padding-left: 30px;"><a href="<?php echo Site::GetBaseRef(); ?>" title="<?php echo ucfirst(Site::GetParms('projectName')); ?>"><img src="<?php echo $parms['logo']; ?>" <?php echo $parms['iwh'][3]; ?> border="0" alt="<?php echo ucfirst(Site::GetParms('projectName')); ?>" /></a></td>
 </tr>
</table>
<table width="800" border="0" cellpadding="0" cellspacing="0" style="background-color: #ffffff;">
 <tr>
  <td style="padding-top: 30px; padding-right: 30px; padding-bottom: 30px; padding-left: 30px;">
   <h1 style="color: #000; font-size: 20px; margin: 0 0 15px 0; font-weight: normal;"><?php echo $parms['subject']; ?></h1>
   <?php include(Site::GetTemplate($this->name, ($parms['self_template'] ? $parms['self_template'] : 'mail'))); ?>
  </td>
 </tr>
</table>
<table width="800" height="5" border="0" cellpadding="0" cellspacing="0">
 <tr>
  <td style="background-color: <?php echo $parms['bottom_line']; ?>;"><img src="<?php echo $parms['pixel']; ?>" width="800" height="5" alt="" /></td>
 </tr>
</table>
<table width="800" border="0" cellpadding="0" cellspacing="0" style="font-family: Arial,Helvetica,clean,sans-serif; font-size: 14px; color: #000000; background-color: #ffffff;">
 <tr>
  <td style="background-color: #ffffff; padding-top: 30px; padding-right: 30px; padding-bottom: 30px; padding-left: 30px;"><?php echo $parms['bottom_address']; ?></td>
 </tr>
</table>
</body>
</html>