<?php
$tmp = $this->table->fields['topic_id']['parms']['items'];
$arr = array(0 => array('id' => 0, 'title' => '[Все топики]'));
if ($tmp) $arr = $arr + $tmp;
?>
<form name="filterForm" action="<?php echo $this->name; ?>-filter.htm" method="post">
<input type="hidden" name="fromFF" value="1" />
<table>
<tr>
 <td class="pr5">Топик</td>
 <td class="pr20"><?php Action::Select('topic_id', Site::GetSession($this->name."-topic_id"), $arr, ' class="field"', array('field' => 'title')); ?></td>
 <td class="pr5">Поиск</td>
 <td class="pr20"><?php Action::Input('like', Site::GetSession($this->name."-like"), ' class="field" style="width: 200px;"'); ?></td>
 <td><input type="image" src="image/btn-search.gif" title="Искать" alt="Искать" /></td>
</tr>
</table>
</form>
