<?php include( Site::GetTemplate( $this->name, 'menu' ) ); ?>
<div class="block coll-8 coll-tablet">
  <h1 class="work-h1">Личные данные</h1>
  <br />
  <?php if (trim($alert)) { ?><p><span class="red"><?php echo $alert; ?></span></p><?php } ?>
  <?php if (trim(preg_replace('/&nbsp;/', ' ', strip_tags($text['content'], '<table><img><ul><li><object><div>')))) echo $text['content']; ?>
  <?php $form->header(); $form->field('old_email'); $form->field('old_nikname'); ?>

    <label>
      <div class="form-name wide">Ф.И.О.:<span class="required">*</span></div>
      <div class="form-value wide"><?php $form->field('fio', ' data-rule-required="true" data-msg-required="Укажите Ваше имя!"'); ?></div>
    </label>
    <div class="clearfix">&nbsp;</div>

    <label>
      <div class="form-name wide">Телефоны:<span class="required">*</span></div>
      <div class="form-value wide"><?php $form->field('phones'); ?></div>
    </label>
    <div class="clearfix">&nbsp;</div>

    <label>
      <div class="form-name wide">Логин (e-mail):<span class="required">*</span></div>
      <div class="form-value wide"><?php $form->field('email', ' data-rule-email="true" data-msg-email="Укажите правильный email!" data-msg-required="Укажите email!" data-rule-required="true"'); ?></div>
    </label>
    <div class="clearfix">&nbsp;</div>

    <label>
      <div class="form-name wide">Сменить пароль:</div>
      <div class="form-value wide"><input type="password" name="password_change" value="" /></div>
    </label>
    <div class="clearfix">&nbsp;</div>

    <label>
      <div class="form-name">&nbsp;</div>
      <div class="form-value"><button type="submit" class="btn wide" type="submit"><span>Отправить данные</span></button></div>
    </label>
    <div class="clearfix">&nbsp;</div>

  <?php $form->footer(); ?>
</div>
