<form name="filterForm" action="<?php echo $this->name; ?>-filter.htm" method="post">
<input type="hidden" name="fromFF" value="1" />
<table>
<tr>
 <td class="pr5">Поиск</td>
 <td class="pr20"><?php Action::Input('like', Site::GetSession($this->name."-like"), ' class="field" style="width: 200px;"'); ?></td>
 <td class="pr20"><?php Action::CheckBox('act', Site::GetSession($this->name."-act")); ?> - Активные</td>
 <td class="pr20"><?php Action::CheckBox('nact', Site::GetSession($this->name."-nact")); ?> - Не активные</td>
 <td><input type="image" src="image/btn-search.gif" title="Искать" alt="Искать" /></td>
</tr>
</table>
</form>