<table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse; width: 100%; font-family: Arial,Helvetica,clean,sans-serif; font-size: 14px; color: #000000; background-color: #ffffff;">
 <tr>
  <td style="background: #ffffff; border: 1px solid #D4D4D4; padding: 3px 5px;">Город</td>
  <td style="background: #ffffff; border: 1px solid #D4D4D4; padding: 3px 5px;"><?php echo $parms['city']; ?></td>
 </tr>
 <tr>
  <td style="background: #ffffff; border: 1px solid #D4D4D4; padding: 3px 5px;">Номер&nbsp;карты</td>
  <td style="background: #ffffff; border: 1px solid #D4D4D4; padding: 3px 5px;"><?php echo $parms['cardnum']; ?></td>
 </tr>
 <tr>
  <td style="background: #ffffff; border: 1px solid #D4D4D4; padding: 3px 5px;" width="1%">Телефон</td>
  <td style="background: #ffffff; border: 1px solid #D4D4D4; padding: 3px 5px;"><?php echo $parms['phone']; ?></td>
 </tr>
 <tr>
  <td style="background: #ffffff; border: 1px solid #D4D4D4; padding: 3px 5px;">E-mail</td>
  <td style="background: #ffffff; border: 1px solid #D4D4D4; padding: 3px 5px;"><?php echo $parms['email']; ?></td>
 </tr>
 <tr>
  <td style="background: #ffffff; border: 1px solid #D4D4D4; padding: 3px 5px;">Имя</td>
  <td style="background: #ffffff; border: 1px solid #D4D4D4; padding: 3px 5px;"><?php echo $parms['fio']; ?></td>
 </tr>
<?php /* ?>
 <tr>
  <td style="background: #ffffff; border: 1px solid #D4D4D4; padding: 3px 5px;">Желаемая дата посещения</td>
  <td style="background: #ffffff; border: 1px solid #D4D4D4; padding: 3px 5px;"><?php echo date( 'd.m.Y H:i', $parms['idate_visit'] ); ?></td>
 </tr>
 <tr>
  <td style="background: #ffffff; border: 1px solid #D4D4D4; padding: 3px 5px;">Ф.И.О.</td>
  <td style="background: #ffffff; border: 1px solid #D4D4D4; padding: 3px 5px;"><?php echo $parms['fio']; ?></td>
 </tr>
 <tr>
  <td style="background: #ffffff; border: 1px solid #D4D4D4; padding: 3px 5px;">День рождения</td>
  <td style="background: #ffffff; border: 1px solid #D4D4D4; padding: 3px 5px;"><?php echo date( 'd.m.Y H:i', $parms['idate_birthday'] ); ?></td>
 </tr>
<?php */ ?>
</table>