<table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse; width: 100%; font-family: Arial,Helvetica,clean,sans-serif; font-size: 14px; color: #000000; background-color: #ffffff;">
 <tr>
  <td style="background: #ffffff; border: 1px solid #D4D4D4; padding: 3px 5px;">Имя</td>
  <td style="background: #ffffff; border: 1px solid #D4D4D4; padding: 3px 5px;"><?php echo $parms['name']; ?></td>
 </tr>
 <tr>
  <td style="background: #ffffff; border: 1px solid #D4D4D4; padding: 3px 5px;" width="1%">E-mail</td>
  <td style="background: #ffffff; border: 1px solid #D4D4D4; padding: 3px 5px;"><?php echo $parms['email']; ?></td>
 </tr>
 <tr>
  <td style="background: #ffffff; border: 1px solid #D4D4D4; padding: 3px 5px;">Отзыв</td>
  <td style="background: #ffffff; border: 1px solid #D4D4D4; padding: 3px 5px;"><?php echo nl2br($parms['text']); ?></td>
 </tr>
</table>