<?php if (trim(preg_replace('/&nbsp;/', ' ', strip_tags($this->menu['content'], '<table><img><ul><li><object><div>')))) echo $this->menu['content']; ?>
<?php if (sizeOf($votes) > 0) { ?>
<?php
$j = 1;
foreach ($votes as $id => $item) {
?>
<div>
<form name="votesForm<?php echo $item['id']; ?>" action="<?php echo $this->menuPath.$this->name; ?>/do" method="post">
<table>
 <input type="hidden" name="votesId" value="<?php echo $item['id']; ?>" />
 <tr><td colspan="2"><strong><?php echo $item['question']; ?></strong></td></tr>
 <?php if (sizeOf($item['vars']) > 0) foreach ($item['vars'] as $var) { ?>
 <tr valign="top">
  <td><?php if ($item['is_checkbox']) { ?><input type="checkbox" name="votesResult[<?php echo $var['id']; ?>]" value="1" /><?php } else { ?><input type="radio" name="votesResult[<?php echo $item['id']; ?>]" value="<?php echo $var['id']; ?>" /><?php } ?></td>
  <td width="99%"><?php echo $var['variant']; ?></td>
 </tr>
 <?php } ?>
 <tr>
  <td>&nbsp;</td>
  <td><?php if ($item['isIP'] || !$item['is_active']) { ?><input type="button" value="Результаты" onClick="document.location.href='<?php echo $this->menuPath.$this->name; ?>/<?php echo $item['id']; ?>-<?php echo $item['href']; ?>';" /><?php } else { ?><input type="submit" value="Проголосовать" /><?php } ?></td>
 </tr>
</table>
</form>
</div>
<?php } ?>
<?php if ($numPages > 1) { ?><div><?php echo Site::GetPageNavigator($page, $numPages, $this->menuPath.'votes/page/%'); ?></div><?php } ?>
<?php } else echo "<p>Опросов нет.</p>"; ?>