<h1>Поиск по администратору</h1>
<form action="<?php echo $this->name; ?>.htm" name="searchAdminForm" method="post">
<div class="filterBgr pt10 pb10 pl10 pr10 mb10">
<table>
<tr>
 <td class="pr5">Поиск</td>
 <td class="pr20"><?php Action::Input('searchadmin', strip_tags($_POST['searchadmin']), ' class="field" style="width: 200px;"'); ?></td>
 <td><input type="image" src="image/btn-search.gif" title="Искать" alt="Искать" /></td>
</tr>
</table>
</div>
</form>
<?php echo $result; ?>