<div style='z-index:99;position:absolute;visibility:hidden;'>
<!-- AWLA -->
<script language="javascript" type="text/javascript"><!--
sg_js="1.0";
sg_r=""+Math.random()+"&r="+escape(document.referrer)+"&pg="+escape(window.location.href);
document.cookie="sg=1; path=/";
sg_r+="&c="+(document.cookie?"1":"0");
if (self!=top) {fr=1;} else {fr=0;}
sg_r+="&fr="+fr;
mt=(new Date()).getTimezoneOffset();
sg_r+="&mt="+mt;
//-->
</script>
<script language="javascript1.1" type="text/javascript"><!--
sg_js="1.1";
sg_r+="&j="+(navigator.javaEnabled()?"1":"0")
//-->
</script>
<script language="javascript1.2" type="text/javascript"><!--
sg_js="1.2";
sg_r+="&wh="+screen.width+'x'+screen.height+"&px="+(((navigator.appName.substring(0,3)=="Mic"))?screen.colorDepth:screen.pixelDepth)
//-->
</script>
<script language="javascript1.3" type="text/javascript"><!--
sg_js="1.3"
//-->
</script>
<script language="javascript" type="text/javascript"><!--
sg_r+="&jv="+sg_js+"&js=1";
document.write("<a href='http://www.interlabs.ru/' title='Веб-дизайн, создание и продвижение сайта'><img "+" src='http://www.site.ru/statdir/stat.php?"+sg_r+"&' border='0' width='1' height='1' alt='Веб-дизайн, создание и продвижение сайта' \/><\/a>");
//-->
</script>
<noscript><a href="http://www.interlabs.ru/" title="Веб-дизайн, создание и продвижение сайта"><img src="http://www.site.ru/statdir/stat.php?nojs=1" border="0" width="1" height="1" alt="Веб-дизайн, создание и продвижение сайта" /></a></noscript>
<!-- /AWLA -->
</div>