<div class="main-slider-container" data-component="site/ui/front/slider" data-attrs="<?php echo htmlspecialchars( json_encode( array( 'prevButton' => '.main-slider-container .main-slider-prev', 'nextButton' => '.main-slider-container .main-slider-next', 'autoSlide' => true, 'autoSlideTimer' => 3000 ) ) ); ?>">
  <div class="slider">
    <?php foreach( $items as $item ) { ?>
      <div class="slide">
        <?php if( !empty( $item['href'] ) ) { ?>
          <a class="link" href="<?php echo $item['href']; ?>"></a>
        <?php } ?>
        <img src="<?php echo $item['picture']; ?>" width="1240" height="468" alt="">
        <?php if( $item['show_text'] ) { ?>
            <div class="slide-text">
              <?php echo $item['text']; ?>
            </div>
        <?php } ?>
      </div>
    <?php } ?>
  </div>

  <div class="main-slider-prev"></div>
  <div class="main-slider-next"></div>
</div>
