<?php
Utils::MetaInit();
$fastNav = Utils::GetFastNavigation();
$h1 = Utils::GetH1( $fastNav );
$fastNav = Utils::CutFastNavigation( $fastNav );
?>
<!DOCTYPE html>
<html<?php echo defined("LANG") ? ' lang="'.LANG.'"' : '' ?>>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" id="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title><?php echo Site::GetParms('titleSite'); ?></title>
    <meta name="description" content="<?php echo htmlspecialchars(Site::GetParms('descriptionSite')); ?>">
    <meta name="keywords" content="<?php echo htmlspecialchars(Site::GetParms('keywordsSite')); ?>">
    <base href="<?php echo Site::GetBaseRef(); ?>">
    <link href="favicon.ico" type="/image/x-icon" rel="shortcut icon">
    <link href="/css/site.css" rel="stylesheet" type="text/css">
  </head>
  <body>
    <div class="wrapper">
      <?php include( Site::GetTemplate( 'layout', 'top' ) ); ?>

      <div class="page">
        <div class="block-group">
          <div class="block">
            <a href="#" class="back m-hide" data-component="site/ui/button-back">Вернуться назад</a>
            <div class="breadcrumbs">
              <?php echo $fastNav; ?>
              <h1><?php echo $h1; ?></h1>
            </div>
          </div>
        </div>
      </div>

      <div class="page">
        <a name="content"></a>
        <div class="block-group js-page-content page-content">
          <?php echo $content; ?>
        </div>
      </div>

      <div class="fixed"></div>
    </div>

    <?php include( Site::GetTemplate( 'layout', 'copyright' ) ); ?>

    <?php /* ?>
    <div class="wrapper maxW minW">
      <div class="header"><?php include(Site::GetTemplate('layout', 'top')); ?></div>
      
      <div class="content">
        <table>
          <tr valign="top">
            <td>
              <?php Utils::GetMenu(); ?>
              <br />
              
              <form name="searchForm" action="/search" method="post" data-validate-style="alert">
                <table class="search">
                  <tr>
                    <td><input type="text" name="search" value="<?php echo (isset($_GET['search']) && $_GET['search'] ? htmlspecialchars(strip_tags($_GET['search'])) : ''); ?>" placeholder="Поиск на сайте" data-rule-required="true" data-msg-required="Укажите поисковый запрос!"  /></td>
                    <td><input type="submit" value="Искать" /></td>
                  </tr>
                </table>
              </form>
            </td>
            <td>
              <div></div>
              <h1></h1>
              <?php echo $content; ?>
            </td>
          </tr>
        </table>
      </div>
      <div class="push"></div>
    </div>
    
    <div class="footer maxW minW"><?php include(Site::GetTemplate('layout', 'copyright')); ?></div>
    <?php */ ?>
  </body>
</html>