<?php
$arr = array(0 => array('id' => 0, 'name' => '[Все заказы]')) + Orders::GetNumbers(array('is_fio' => true));
?>
<form name="filterForm" action="<?php echo $this->name; ?>-filter.htm" method="post">
<input type="hidden" name="fromFF" value="1" />
<table>
<tr>
 <td class="pr5">Заказ</td>
 <td class="pr20"><?php Action::Select('orders_id', Site::GetSession($this->name."-orders_id"), $arr, ' class="field"', array('field' => 'name')); ?></td>
 <td class="pr5">Поиск</td>
 <td class="pr20"><?php Action::Input('like', Site::GetSession($this->name."-like"), ' class="field" style="width: 200px;"'); ?></td>
 <td><input type="image" src="image/btn-search.gif" title="Искать" alt="Искать" /></td>
</tr>
</table>
</form>
