<?php include(Site::GetTemplate('forum', 'navi')); ?>
<table width="100%">
<tr align="center">
 <td><strong><a href="forum.htm" title="Форум">Форум</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="cat_<?php echo $forum['cat_id']; ?>.htm" title="<?php echo htmlspecialchars($cat['title']); ?>"><?php echo $cat['title']; ?></a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="forum_<?php echo $forum['id']; ?>.htm" title="<?php echo htmlspecialchars($forum['name']); ?>"><?php echo $forum['name']; ?></a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<?php echo $topic['title']; ?></strong></td>
 <td nowrap="nowrap" align="right">
  <?php if ($moderator) { ?><a href="topic<?php echo ($moderate ? '' : '_moderate'); ?>_<?php echo $this->parms['topic']; ?>.htm" title="<?php echo ($moderate ? 'Модерирование выход' : 'Модерировать'); ?>"><?php echo ($moderate ? 'Модер.[Выход]' : '[Модерировать]'); ?></a><br /><?php } ?>
  <noindex><a href="post_new_<?php echo $this->parms['topic']; ?>.htm" title="Новое сообщение">Новое сообщение</a></noindex>
 </td>
</tr>
</table>
<table class="table w100">
<tr>
 <th width="20%">Информация</th>
 <th width="80%">Сообщение</th>
 <?php if ($moderate) echo "<th>Удалить</th>"; ?>
</tr>
<?php if (sizeOf($posts) > 0) { ?>
<?php if ($numPages > 1) { ?><tr class="td1"><td colspan="3" align="right"><?php if ($numPages > 1) echo Site::GetPageNavigator($page, $numPages, "topic".($moderate ? '_moderate' : '')."_".$this->parms["topic"]."_%.htm")."</p>"; ?></td></tr><?php } ?>
<?php foreach ($posts as $id => $item) { ?>
<?php if ($moderate) { ?>
<form name="postForm<?php echo $id; ?>" method="post" action="post_change.htm">
<input type="hidden" value="<?php echo $item['text_id']; ?>" name="post_text_id" />
<input type="hidden" value="<?php echo $id; ?>" name="post_id" />
<input type="hidden" value="<?php echo $this->parms['topic']; ?>" name="topic_id" />
<?php } ?>
<tr class="td1" valign="top">
 <td>
  <b>Автор: </b><a href="users_<?php echo $item['poster_id']; ?>.htm"><?php echo $item['user']['nikname']; ?></a><br />
  <b>Сообщений: </b><?php echo Posts::GetCountRows(array('poster_id' => $item['poster_id'])); ?><br />
  <b>На форуме c: </b><?php echo date("d.m.y", $item['user']['idate']); ?>
  <?php if ($item['user']['avatar'] && file_exists(Site::GetParms('absolutePath').$item['user']['avatar'])) { $iwh = GetImageSize(Site::GetParms('absolutePath').$item['user']['avatar']); ?><br /><br /><div><a href="users_<?php echo $item['poster_id']; ?>.htm"><img src="<?php echo $item['user']['avatar']; ?>" <?php echo $iwh[3]; ?> alt="<?php echo htmlspecialchars($item['user']['nikname']); ?>" /></a></div><?php } ?>
 </td>
 <td>
  <?php if (!$moderate) { ?>
   <div><?php echo preg_replace(array("/\[quote\]/", '/\[\/quote\]/', '/\[url ([^\]]+)\]/', '/\[\/url\]/'), array('<div class="quote">', '</div>', '<a href="\\1">', '</a>'), nl2br($item['text'])); ?></div><br />
   <div class="small"><?php echo $item['user']['sig']; ?></div>
  <?php } else { ?><textarea rows="10" cols="100" name="text" class="input w100"><?php echo $item['text']; ?></textarea><?php } ?>
 </td>
<?php if ($moderate) { ?><td align="center"><input type="checkbox" name="is_del" /></td><?php } ?>
</tr>
<tr>
 <td colspan="3" align="right">
  <a href="posttext_<?php echo $item['id']; ?>.htm" title="Ссылка на сообщение">Ссылка на сообщение</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <noindex><a href="usermail_<?php echo $item['user']['password']; ?>.htm" title="Послать email автору">Послать e-mail</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="post_new_<?php echo $this->parms['topic'].'_'.$id; ?>.htm" title="Ответить">Ответить</a></noindex>
  <?php if ($moderate) { ?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#" title="Изменить сообщение" onclick="document.postForm<?php echo $id; ?>.submit(); return false;">Изменить</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#" title="Удалить сообщение" onclick="document.postForm<?php echo $id; ?>.submit(); return false;">Удалить</a><?php } else { ?>
  <?php if (defined("UID") && UID > 0 && UID == $item['poster_id']) { ?>
   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="post_edit_<?php echo $id; ?>.htm" title="Редактировать сообщение">Редактировать</a>
   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="post_delete_<?php echo $id; ?>.htm" title="Удалить сообщение">Удалить</a>
  <?php } ?>
  <?php } ?>
 </td>
</tr>
<?php if ($moderate) {?></form><?php } ?>
<?php } ?>
<?php if ($numPages > 1) { ?><tr class="td1"><td colspan="3" align="right"><?php if ($numPages > 1) echo Site::GetPageNavigator($page, $numPages, "topic".($moderate ? '_moderate' : '')."_".$this->parms["topic"]."_%.htm")."</p>"; ?></td></tr><?php } ?>
<?php } else { ?>
<tr class="td1"><td width="100%" colspan="3">Тема не содержит сообщений.</td></tr>
<?php } ?>
</table>
<br />
<table width="100%">
<tr align="center">
 <td><strong><a href="forum.htm" title="Форум">Форум</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="cat_<?php echo $forum['cat_id']; ?>.htm" title="<?php echo htmlspecialchars($cat['title']); ?>"><?php echo $cat['title']; ?></a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="forum_<?php echo $forum['id']; ?>.htm" title="<?php echo htmlspecialchars($forum['name']); ?>"><?php echo $forum['name']; ?></a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<?php echo $topic['title']; ?></strong></td>
 <td nowrap="nowrap" align="right">
  <?php if ($moderator) { ?><a href="topic<?php echo ($moderate ? '' : '_moderate'); ?>_<?php echo $this->parms['topic']; ?>.htm" title="<?php echo ($moderate ? 'Модерирование выход' : 'Модерировать'); ?>"><?php echo ($moderate ? 'Модер.[Выход]' : '[Модерировать]'); ?></a><br /><?php } ?>
  <noindex><a href="post_new_<?php echo $this->parms['topic']; ?>.htm" title="Новое сообщение">Новое сообщение</a></noindex>
 </td>
</tr>
</table>
<br />
<a name="last"></a>
<form name="postForm2" method="post" action="post_add.htm">
<input type="hidden" value="<?php echo $this->parms['topic']; ?>" name="topic_id" />
<table align="center" width="50%">
 <tr class="td1" valign="top">
  <td style="padding-left: 10px;">Форма быстрого ответа в теме: <?php echo $topic['title']; ?></td>
  <td width="99%" align="center">
   <textarea name="text" class="input w100" rows="10" cols="100"><?php if (Site::GetSession('textAddPostForum')) { echo Site::GetSession('textAddPostForum'); Site::SetSession('textAddPostForum', ''); } ?></textarea><br />
   <input type="submit" value="Написать сообщение" />
  </td>
 </tr>
</table>
</form>